### ISSUE TITLE
Pods are showing error

### ISSUE THREAD

**Issue by nitinrajput1997** [Telecominfraproject/wlan-cloud-ucentral-deploy#52]
Half of the pods shows this error

kubectl logs po/owprov-5c6dfd4d95-n2tln
File not found: Private key file: /owprov-data/certs/restapi-key.pem

**Comment by dunaev-opsfleet** [comment]
This is happening because you probably haven't set the required values for this
You should check example values in services repositories for the template. For example https://github.com/Telecominfraproject/wlan-cloud-owprov/blob/main/helm/values.yaml#L201
Example of passed value may be found in our testing repository - https://github.com/Telecominfraproject/wlan-testing/blob/master/helm/ucentral/values.ucentral-qa.yaml#L32
Another way to get rid of this issue is to use cert-manager managed certificates as described in https://github.com/Telecominfraproject/wlan-cloud-ucentral-deploy/tree/main/chart#private-rest-api-cert-manager-managed-certificates , but even with this setup certificate for Websocket endpoint for OWGW will be required, but for the tests you may try using the one that's also generated by cert-manager

**Comment by sohaib1khan** [comment]
> This is happening because you probably haven't set the required values for this You should check example values in services repositories for the template. For example https://github.com/Telecominfraproject/wlan-cloud-owprov/blob/main/helm/values.yaml#L201 Example of passed value may be found in our testing repository - https://github.com/Telecominfraproject/wlan-testing/blob/master/helm/ucentral/values.ucentral-qa.yaml#L32 Another way to get rid of this issue is to use cert-manager managed certificates as described in https://github.com/Telecominfraproject/wlan-cloud-ucentral-deploy/tree/main/chart#private-rest-api-cert-manager-managed-certificates , but even with this setup certificate for Websocket endpoint for OWGW will be required, but for the tests you may try using the one that's also generated by cert-manager


Hi @dunaev-opsfleet , I'm deploying ucentral using the helm method. i have provided the appropriate certs but am unable to access the UI. where do I need to specify the FQDN in the configuration? Could you please kindly provide those steps? I also noticed in the logs for pod owgw-6975f4586d-nm4zl  that it's unable to establish a connection. 


Deployed with Certs: 

$ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
kafka-0                        1/1     Running   2          113m
owanalytics-69f55bd8bb-6j2km   1/1     Running   0          113m
owfms-54fcddbb8-w8gz5          1/1     Running   0          113m
owgw-6975f4586d-nm4zl          1/1     Running   0          113m
owgwui-ff9dc88b-pnmqp          1/1     Running   0          113m
owprov-56c9c688b-6srmg         1/1     Running   0          113m
owprovui-6b784c8c94-fssdd      1/1     Running   0          113m
owsec-6b467745d5-xv4x7         1/1     Running   0          113m
owsub-655775f67f-vt2g9         1/1     Running   0          113m
proxy-65ff54f8bc-j4fvr         1/1     Running   0          113m
proxy-65ff54f8bc-nwrv5         1/1     Running   0          113m
proxy-65ff54f8bc-r2v8n         1/1     Running   0          113m
zookeeper-0                    1/1     Running   0          113m

**Comment by dunaev-opsfleet** [comment]
@sohaib1khan Hello,
> I'm deploying ucentral using the helm method. i have provided the appropriate certs but am unable to access the UI. where do I need to specify the FQDN in the configuration?
In order to expose OWGW-UI, you need to set external-dns annotation to Ingress. You can see example in https://github.com/Telecominfraproject/wlan-cloud-ucentral-deploy/blob/main/chart/environment-values/values.aws.yaml#L22 
> I also noticed in the logs for pod owgw-6975f4586d-nm4zl that it's unable to establish a connection.
Could you please give me an exact logs? If errors are saying something about not being able to connect to Kafka, it may happen on initial kafka startup, but it should disappear in time. If you'll see list of other services endpoints in the logs, it means that it is configured correctly

**Comment by sohaib1khan** [comment]
Hello @dunaev-opsfleet , 

Thank you so much for your help! I tried your suggestions and was able to successfully expose owgw-ui. I have tried the default logins from [here](https://github.com/dunaev-opsfleet/ucentral-deployment/blob/master/cloud-sdk-installation/helm-deployment.md)  and am unable to login. Could you point me in the right direction where I would need to correct this? I have tried editing this line
https://github.com/Telecominfraproject/wlan-cloud-ucentral-deploy/blob/644ff61e873a96b66c86d3dc10ae114d0e9cad9d/chart/environment-values/values.aws.yaml#L34

**Comment by dunaev-opsfleet** [comment]
You should set value `13268b7daa751240369d125e79c873bd8dd3bef7981bdfd38ea03dbb1fbe7dcf` (taken from https://github.com/Telecominfraproject/wlan-cloud-ucentralsec/blob/main/helm/values.yaml#L213), then default credentials from https://github.com/dunaev-opsfleet/ucentral-deployment/blob/master/cloud-sdk-installation/helm-deployment.md#deploy-tip-controller will be working
Else you may generate your own credentials using instructions from https://github.com/Telecominfraproject/wlan-cloud-ucentralsec/#default-username-and-password

**Comment by sohaib1khan** [comment]
Hi @dunaev-opsfleet 

I tried the suggested steps and was still unsuccessful in logging in.  

Is it possible to debug any connection issues between the services? like would I be able to confirm if owgwui is communicating with owsec? Is there some additional logging that can be enabled? 

Thank you so much for your help! I greatly appreciate it!

**Comment by dunaev-opsfleet** [comment]
OWGW-UI isn't communicating with OWSec since it's frontend application - basically all requests are sent from your browser to OWSEC. With that in mind you may open browser developer tools and see the requests that are made to OWSec to understand what's happening
